version: '3.8'

services:
  log-generator:
    image: python:3.9
    container_name: log-generator
    volumes:
      - ./log_generator:/app
    command: python /app/log_generator.py

  rsyslog:
    image: rsyslog/rsyslog
    container_name: rsyslog
    ports:
      - "514:514/udp"
    volumes:
      - ./rsyslog:/etc/rsyslog.d
      - ./logs:/var/log

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:9092"

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
    volumes:
      - ./ftp:/home/ftpusers

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  ilm-setup:
    image: python:3.9
    container_name: ilm-setup
    volumes:
      - ./ilm:/app
    command: python /app/setup_ilm.py
    depends_on:
      - elasticsearch
      - kafka

