version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8090:8090"
      - "8008:8008"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/local.html:/usr/share/nginx/html/local.html
      - ./nginx/htpasswd:/etc/nginx/.htpasswd

